lexemplaire:
    resource: "@LexemplaireBundle/Controller/"
    type:     annotation
    prefix:   /home
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
