<?php

namespace LexemplaireBundle\Repository;

/**
 * essaiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class essaiRepository extends \Doctrine\ORM\EntityRepository
{
}
