<?php

namespace LexemplaireBundle\Repository;

/**
 * MiseAJourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MiseAJourRepository extends \Doctrine\ORM\EntityRepository
{
}
